server:
  port: 8080
spring:
  ai:
    openai:
      api-key: "sk-xxxxxx" # 安全起见，从系统环境变量读取
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.5